name: Database Update Cron Job

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Trigger database update
        run: |
          curl -X GET "${{ secrets.VERCEL_URL }}/api/cron/update-database" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
